export const FETCH_CAFE_BOARD_LIST = "FETCH_CAFE_BOARD_LIST"
export const FETCH_CAFE_BOARD = "FETCH_CAFE_BOARD"
export const FETCH_MENU_LISTS = "FETCH_MENU_LISTS"
export const FETCH_CAFE_IMG_LISTS = "FETCH_CAFE_IMG_LISTS"

export const FETCH_REVIEW_LIST = "FETCH_REVIEW_LIST"
export const FETCH_REVIEW = "FETCH_REVIEW"
export const FETCH_LIKES_LIST = "FETCH_LIKES_LIST"

export const FETCH_QNA_LIST = "FETCH_QNA_LIST"
export const FETCH_QNA_LISTS = "FETCH_QNA_LISTS"
