export const FETCH_CAFE_BOARD_LIST = "FETCH_CAFE_BOARD_LIST"
export const FETCH_CAFE_BOARD = "FETCH_CAFE_BOARD"
export const FETCH_CAFE_NO = "FETCH_CAFE_NO"
export const FETCH_MENU_LISTS = "FETCH_MENU_LISTS"
export const FETCH_CAFE_IMG_LISTS = "FETCH_CAFE_IMG_LISTS"

export const FETCH_REVIEW_LIST = "FETCH_REVIEW_LIST"
export const FETCH_REVIEW = "FETCH_REVIEW"
export const FETCH_HELPS_LIST = "FETCH_HELPS_LIST"

export const FETCH_QNA_LIST = "FETCH_QNA_LIST"

export const FETCH_USER = "FETCH_USER"
export const FETCH_USER_INFO = "FETCH_USER_INFO"

export const FETCH_MY_HELPS_LIST = "FETCH_MY_HELPS_LIST"
export const FETCH_HELP = "FETCH_HELP"

//공지사항
export const FETCH_NOTICE_BOARD = "FETCH_NOTICE_BOARD"
export const FETCH_NOTICE_BOARD_LIST = "FETCH_NOTICE_BOARD_LIST"
