//CafeMyPage 
/*export const FETCH_CAFE_BOARD_LIST = 'FETCH_CAFE_BOARD_LIST'
export const FETCH_CAFE_BOARD = 'FETCH_CAFE_BOARD'*/
export const FETCH_MENU_LISTS = 'FETCH_MENU_LISTS'
export const FETCH_MENU_SIG_LISTS = 'FETCH_MENU_SIG_LISTS'
export const FETCH_MENU_SOLD_OUT_LISTS = 'FETCH_MENU_SOLD_OUT_LISTS'